/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-06-05 12:23:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1780662026558L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write(" <title>AI.Tech - Artificial Intelligence HTML Template</title>\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Ubuntu:wght@500;700&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <!-- Navbar Start -->\r\n");
      out.write("    <div class=\"container-fluid sticky-top\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <nav class=\"navbar navbar-expand-lg navbar-dark p-0\">\r\n");
      out.write("                <a href=\"index.jsp\" class=\"navbar-brand\">\r\n");
      out.write("                    <h1 class=\"text-white\">AI<span class=\"text-dark\">.</span>Tech</h1>\r\n");
      out.write("                </a>\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggler ms-auto me-0\" data-bs-toggle=\"collapse\"\r\n");
      out.write("                    data-bs-target=\"#navbarCollapse\">\r\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\">\r\n");
      out.write("                    <div class=\"navbar-nav ms-auto\">\r\n");
      out.write("                        <a href=\"index.jsp\" class=\"nav-item nav-link active\">Home</a>\r\n");
      out.write("                        <a href=\"about.jsp\" class=\"nav-item nav-link\">About</a>\r\n");
      out.write("                        <a href=\"seller.jsp\" class=\"nav-item nav-link\">Seller</a>\r\n");
      out.write("                        <a href=\"customer.jsp\" class=\"nav-item nav-link\">Customer</a>\r\n");
      out.write("                        <a href=\"Admin.jsp\" class=\"nav-item nav-link\">Admin</a>\r\n");
      out.write("                        <div class=\"nav-item dropdown\">\r\n");
      out.write("                            <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">Pages</a>\r\n");
      out.write("                            <div class=\"dropdown-menu bg-light mt-2\">\r\n");
      out.write("                                <a href=\"feature.html\" class=\"dropdown-item\">Features</a>\r\n");
      out.write("                                <a href=\"team.html\" class=\"dropdown-item\">Our Team</a>\r\n");
      out.write("                                <a href=\"faq.html\" class=\"dropdown-item\">FAQs</a>\r\n");
      out.write("                                <a href=\"testimonial.html\" class=\"dropdown-item\">Testimonial</a>\r\n");
      out.write("                                <a href=\"404.html\" class=\"dropdown-item\">404 Page</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <a href=\"contact.jsp\" class=\"nav-item nav-link\">Contact</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <butaton type=\"button\" class=\"btn text-white p-0 d-none d-lg-block\" data-bs-toggle=\"modal\"\r\n");
      out.write("                        data-bs-target=\"#searchModal\"><i class=\"fa fa-search\"></i></butaton>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Navbar End -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>AI.Tech - Artificial Intelligence HTML Template</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Spinner Start -->\r\n");
      out.write("    <div id=\"spinner\"\r\n");
      out.write("        class=\"show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center\">\r\n");
      out.write("        <div class=\"spinner-grow text-primary\" style=\"width: 3rem; height: 3rem;\" role=\"status\">\r\n");
      out.write("            <span class=\"sr-only\">Loading...</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Spinner End -->\r\n");
      out.write("    <!-- Hero Start -->\r\n");
      out.write("    <div class=\"container-fluid pt-5 bg-primary hero-header\">\r\n");
      out.write("        <div class=\"container pt-5\">\r\n");
      out.write("            <div class=\"row g-5 pt-5\">\r\n");
      out.write("                <div class=\"col-lg-6 align-self-center text-center text-lg-start mb-lg-5\">\r\n");
      out.write("                    <h1 class=\"display-4 text-white mb-4 animated slideInRight\">About Us</h1>\r\n");
      out.write("                    <nav aria-label=\"breadcrumb\">\r\n");
      out.write("                        <ol class=\"breadcrumb justify-content-center justify-content-lg-start mb-0\">\r\n");
      out.write("                            <li class=\"breadcrumb-item\"><a class=\"text-white\" href=\"#\">Home</a></li>\r\n");
      out.write("                            <li class=\"breadcrumb-item\"><a class=\"text-white\" href=\"#\">Pages</a></li>\r\n");
      out.write("                            <li class=\"breadcrumb-item text-white active\" aria-current=\"page\">About Us</li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 align-self-end text-center text-lg-end\">\r\n");
      out.write("                    <img class=\"img-fluid\" src=\"img/hero-img.png\" alt=\"\" style=\"max-height: 300px;\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Hero End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Full Screen Search Start -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"searchModal\" tabindex=\"-1\">\r\n");
      out.write("        <div class=\"modal-dialog modal-fullscreen\">\r\n");
      out.write("            <div class=\"modal-content\" style=\"background: rgba(20, 24, 62, 0.7);\">\r\n");
      out.write("                <div class=\"modal-header border-0\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-square bg-white btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("                        aria-label=\"Close\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body d-flex align-items-center justify-content-center\">\r\n");
      out.write("                    <div class=\"input-group\" style=\"max-width: 600px;\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control bg-transparent border-light p-3\"\r\n");
      out.write("                            placeholder=\"Type search keyword\">\r\n");
      out.write("                        <button class=\"btn btn-light px-4\"><i class=\"bi bi-search\"></i></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Full Screen Search End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- About Start -->\r\n");
      out.write("    <div class=\"container-fluid py-5\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"row g-5 align-items-center\">\r\n");
      out.write("                <div class=\"col-lg-6 wow fadeIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                    <div class=\"about-img\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/about-img.jpg\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 wow fadeIn\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                    <div class=\"btn btn-sm border rounded-pill text-primary px-3 mb-3\">About Us</div>\r\n");
      out.write("                    <h1 class=\"mb-4\">We Make Your Business Smarter with Artificial Intelligence</h1>\r\n");
      out.write("                    <p class=\"mb-4\">Tempor erat elitr rebum at clita. Diam dolor diam ipsum et tempor sit. Aliqu diam\r\n");
      out.write("                        amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus\r\n");
      out.write("                        clita duo justo et tempor eirmod magna dolore erat amet</p>\r\n");
      out.write("                    <p class=\"mb-4\">Aliqu diam amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no\r\n");
      out.write("                        labore lorem sit. Sanctus clita duo justo et tempor.</p>\r\n");
      out.write("                    <div class=\"row g-3\">\r\n");
      out.write("                        <div class=\"col-sm-6\">\r\n");
      out.write("                            <h6 class=\"mb-3\"><i class=\"fa fa-check text-primary me-2\"></i>Award Winning</h6>\r\n");
      out.write("                            <h6 class=\"mb-0\"><i class=\"fa fa-check text-primary me-2\"></i>Professional Staff</h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-6\">\r\n");
      out.write("                            <h6 class=\"mb-3\"><i class=\"fa fa-check text-primary me-2\"></i>24/7 Support</h6>\r\n");
      out.write("                            <h6 class=\"mb-0\"><i class=\"fa fa-check text-primary me-2\"></i>Fair Prices</h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"d-flex align-items-center mt-4\">\r\n");
      out.write("                        <a class=\"btn btn-primary rounded-pill px-4 me-3\" href=\"\">Read More</a>\r\n");
      out.write("                        <a class=\"btn btn-outline-primary btn-square me-3\" href=\"\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-outline-primary btn-square me-3\" href=\"\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-outline-primary btn-square me-3\" href=\"\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-outline-primary btn-square\" href=\"\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- About End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Feature Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-primary feature pt-5\">\r\n");
      out.write("        <div class=\"container pt-5\">\r\n");
      out.write("            <div class=\"row g-5\">\r\n");
      out.write("                <div class=\"col-lg-6 align-self-center mb-md-5 pb-md-5 wow fadeIn\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                    <div class=\"btn btn-sm border rounded-pill text-white px-3 mb-3\">Why Choose Us</div>\r\n");
      out.write("                    <h1 class=\"text-white mb-4\">We're Best in AI Industry with 10 Years of Experience</h1>\r\n");
      out.write("                    <p class=\"text-light mb-4\">Aliqu diam amet diam et eos labore. Clita erat ipsum et lorem et sit, sed\r\n");
      out.write("                        stet no labore lorem sit. Sanctus clita duo justo et tempor</p>\r\n");
      out.write("                    <div class=\"d-flex align-items-center text-white mb-3\">\r\n");
      out.write("                        <div class=\"btn-sm-square bg-white text-primary rounded-circle me-3\">\r\n");
      out.write("                            <i class=\"fa fa-check\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span>Diam dolor diam ipsum et tempor sit</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"d-flex align-items-center text-white mb-3\">\r\n");
      out.write("                        <div class=\"btn-sm-square bg-white text-primary rounded-circle me-3\">\r\n");
      out.write("                            <i class=\"fa fa-check\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span>Diam dolor diam ipsum et tempor sit</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"d-flex align-items-center text-white mb-3\">\r\n");
      out.write("                        <div class=\"btn-sm-square bg-white text-primary rounded-circle me-3\">\r\n");
      out.write("                            <i class=\"fa fa-check\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span>Diam dolor diam ipsum et tempor sit</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row g-4 pt-3\">\r\n");
      out.write("                        <div class=\"col-sm-6\">\r\n");
      out.write("                            <div class=\"d-flex rounded p-3\" style=\"background: rgba(256, 256, 256, 0.1);\">\r\n");
      out.write("                                <i class=\"fa fa-home fa-3x text-white\"></i>\r\n");
      out.write("                                <div class=\"ms-3\">\r\n");
      out.write("                                    <h2 class=\"text-white mb-0\" data-toggle=\"counter-up\">9999</h2>\r\n");
      out.write("                                    <p class=\"text-white mb-0\">Happy Clients</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-6\">\r\n");
      out.write("                            <div class=\"d-flex rounded p-3\" style=\"background: rgba(256, 256, 256, 0.1);\">\r\n");
      out.write("                                <i class=\"fa fa-home fa-3x text-white\"></i>\r\n");
      out.write("                                <div class=\"ms-3\">\r\n");
      out.write("                                    <h2 class=\"text-white mb-0\" data-toggle=\"counter-up\">9999</h2>\r\n");
      out.write("                                    <p class=\"text-white mb-0\">Project Complete</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 align-self-end text-center text-md-end wow fadeIn\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                    <img class=\"img-fluid\" src=\"img/feature.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Feature End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Team Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-light py-5\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"row g-5 align-items-center\">\r\n");
      out.write("                <div class=\"col-lg-5 wow fadeIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                    <div class=\"btn btn-sm border rounded-pill text-primary px-3 mb-3\">Our Team</div>\r\n");
      out.write("                    <h1 class=\"mb-4\">Meet Our Experienced Team Members</h1>\r\n");
      out.write("                    <p class=\"mb-4\">Tempor erat elitr rebum at clita. Diam dolor diam ipsum et tempor sit. Aliqu diam\r\n");
      out.write("                        amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus\r\n");
      out.write("                        clita duo justo et tempor eirmod magna dolore erat amet</p>\r\n");
      out.write("                    <a class=\"btn btn-primary rounded-pill px-4\" href=\"\">Read More</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-7\">\r\n");
      out.write("                    <div class=\"row g-4\">\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <div class=\"row g-4\">\r\n");
      out.write("                                <div class=\"col-12 wow fadeIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                                    <div class=\"team-item bg-white text-center rounded p-4 pt-0\">\r\n");
      out.write("                                        <img class=\"img-fluid rounded-circle p-4\" src=\"img/team-1.jpg\" alt=\"\">\r\n");
      out.write("                                        <h5 class=\"mb-0\">Boris Johnson</h5>\r\n");
      out.write("                                        <small>Founder & CEO</small>\r\n");
      out.write("                                        <div class=\"d-flex justify-content-center mt-3\">\r\n");
      out.write("                                            <a class=\"btn btn-square btn-primary m-1\" href=\"\"><i\r\n");
      out.write("                                                    class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                                            <a class=\"btn btn-square btn-primary m-1\" href=\"\"><i\r\n");
      out.write("                                                    class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                                            <a class=\"btn btn-square btn-primary m-1\" href=\"\"><i\r\n");
      out.write("                                                    class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                                            <a class=\"btn btn-square btn-primary m-1\" href=\"\"><i\r\n");
      out.write("                                                    class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-12 wow fadeIn\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                                    <div class=\"team-item bg-white text-center rounded p-4 pt-0\">\r\n");
      out.write("                                        <img class=\"img-fluid rounded-circle p-4\" src=\"img/team-2.jpg\" alt=\"\">\r\n");
      out.write("                                        <h5 class=\"mb-0\">Adam Crew</h5>\r\n");
      out.write("                                        <small>Executive Manager</small>\r\n");
      out.write("                                        <div class=\"d-flex justify-content-center mt-3\">\r\n");
      out.write("                                            <a class=\"btn btn-square btn-primary m-1\" href=\"\"><i\r\n");
      out.write("                                                    class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                                            <a class=\"btn btn-square btn-primary m-1\" href=\"\"><i\r\n");
      out.write("                                                    class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                                            <a class=\"btn btn-square btn-primary m-1\" href=\"\"><i\r\n");
      out.write("                                                    class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                                            <a class=\"btn btn-square btn-primary m-1\" href=\"\"><i\r\n");
      out.write("                                                    class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6 pt-md-4\">\r\n");
      out.write("                            <div class=\"row g-4\">\r\n");
      out.write("                                <div class=\"col-12 wow fadeIn\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                                    <div class=\"team-item bg-white text-center rounded p-4 pt-0\">\r\n");
      out.write("                                        <img class=\"img-fluid rounded-circle p-4\" src=\"img/team-3.jpg\" alt=\"\">\r\n");
      out.write("                                        <h5 class=\"mb-0\">Kate Winslet</h5>\r\n");
      out.write("                                        <small>Co Founder</small>\r\n");
      out.write("                                        <div class=\"d-flex justify-content-center mt-3\">\r\n");
      out.write("                                            <a class=\"btn btn-square btn-primary m-1\" href=\"\"><i\r\n");
      out.write("                                                    class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                                            <a class=\"btn btn-square btn-primary m-1\" href=\"\"><i\r\n");
      out.write("                                                    class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                                            <a class=\"btn btn-square btn-primary m-1\" href=\"\"><i\r\n");
      out.write("                                                    class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                                            <a class=\"btn btn-square btn-primary m-1\" href=\"\"><i\r\n");
      out.write("                                                    class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-12 wow fadeIn\" data-wow-delay=\"0.7s\">\r\n");
      out.write("                                    <div class=\"team-item bg-white text-center rounded p-4 pt-0\">\r\n");
      out.write("                                        <img class=\"img-fluid rounded-circle p-4\" src=\"img/team-4.jpg\" alt=\"\">\r\n");
      out.write("                                        <h5 class=\"mb-0\">Cody Gardner</h5>\r\n");
      out.write("                                        <small>Project Manager</small>\r\n");
      out.write("                                        <div class=\"d-flex justify-content-center mt-3\">\r\n");
      out.write("                                            <a class=\"btn btn-square btn-primary m-1\" href=\"\"><i\r\n");
      out.write("                                                    class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                                            <a class=\"btn btn-square btn-primary m-1\" href=\"\"><i\r\n");
      out.write("                                                    class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                                            <a class=\"btn btn-square btn-primary m-1\" href=\"\"><i\r\n");
      out.write("                                                    class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                                            <a class=\"btn btn-square btn-primary m-1\" href=\"\"><i\r\n");
      out.write("                                                    class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Team End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Newsletter Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-primary newsletter py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row g-5 align-items-center\">\r\n");
      out.write("                <div class=\"col-md-5 ps-lg-0 pt-5 pt-md-0 text-start wow fadeIn\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                    <img class=\"img-fluid\" src=\"img/newsletter.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-7 py-5 newsletter-text wow fadeIn\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                    <div class=\"btn btn-sm border rounded-pill text-white px-3 mb-3\">Newsletter</div>\r\n");
      out.write("                    <h1 class=\"text-white mb-4\">Let's subscribe the newsletter</h1>\r\n");
      out.write("                    <div class=\"position-relative w-100 mt-3 mb-2\">\r\n");
      out.write("                        <input class=\"form-control border-0 rounded-pill w-100 ps-4 pe-5\" type=\"text\"\r\n");
      out.write("                            placeholder=\"Enter Your Email\" style=\"height: 48px;\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn shadow-none position-absolute top-0 end-0 mt-1 me-2\"><i\r\n");
      out.write("                                class=\"fa fa-paper-plane text-primary fs-4\"></i></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <small class=\"text-white-50\">Diam sed sed dolor stet amet eirmod</small>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Newsletter End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-dark text-white-50 footer pt-5\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"row g-5\">\r\n");
      out.write("                <div class=\"col-md-6 col-lg-3 wow fadeIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                    <a href=\"index.html\" class=\"d-inline-block mb-3\">\r\n");
      out.write("                        <h1 class=\"text-white\">AI<span class=\"text-primary\">.</span>Tech</h1>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <p class=\"mb-0\">Tempor erat elitr rebum at clita. Diam dolor diam ipsum et tempor sit. Aliqu diam\r\n");
      out.write("                        amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus\r\n");
      out.write("                        clita duo justo et tempor</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-3 wow fadeIn\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Get In Touch</h5>\r\n");
      out.write("                    <p><i class=\"fa fa-map-marker-alt me-3\"></i>123 Street, New York, USA</p>\r\n");
      out.write("                    <p><i class=\"fa fa-phone-alt me-3\"></i>+012 345 67890</p>\r\n");
      out.write("                    <p><i class=\"fa fa-envelope me-3\"></i>info@example.com</p>\r\n");
      out.write("                    <div class=\"d-flex pt-2\">\r\n");
      out.write("                        <a class=\"btn btn-outline-light btn-social\" href=\"\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-outline-light btn-social\" href=\"\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-outline-light btn-social\" href=\"\"><i class=\"fab fa-youtube\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-outline-light btn-social\" href=\"\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-outline-light btn-social\" href=\"\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-3 wow fadeIn\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Popular Link</h5>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">About Us</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Contact Us</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Privacy Policy</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Terms & Condition</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Career</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-3 wow fadeIn\" data-wow-delay=\"0.7s\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Our Services</h5>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Robotic Automation</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Machine learning</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Predictive Analysis</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Data Science</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Robot Technology</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container wow fadeIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("            <div class=\"copyright\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-6 text-center text-md-start mb-3 mb-md-0\">\r\n");
      out.write("                        &copy; <a class=\"border-bottom\" href=\"#\">Your Site Name</a>, All Right Reserved.\r\n");
      out.write("\r\n");
      out.write("                        <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from \"https://htmlcodex.com/credit-removal\". Thank you for your support. ***/-->\r\n");
      out.write("                        Designed By <a class=\"border-bottom\" href=\"https://htmlcodex.com\">HTML Codex</a> Distributed By <a class=\"border-bottom\" href=\"https://themewagon.com\">ThemeWagon</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 text-center text-md-end\">\r\n");
      out.write("                        <div class=\"footer-menu\">\r\n");
      out.write("                            <a href=\"\">Home</a>\r\n");
      out.write("                            <a href=\"\">Cookies</a>\r\n");
      out.write("                            <a href=\"\">Help</a>\r\n");
      out.write("                            <a href=\"\">FAQs</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Back to Top -->\r\n");
      out.write("    <a href=\"#\" class=\"btn btn-lg btn-primary btn-lg-square back-to-top pt-2\"><i class=\"bi bi-arrow-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- JavaScript Libraries -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/wow/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/easing/easing.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/counterup/counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
