/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-06-23 07:37:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import dao.ProductDao;
import models.Product;
import java.util.List;
import models.Customer;
import dao.CartDao;
import models.Cart;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/customer-header.jsp", Long.valueOf(1782193976900L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("models.Cart");
    _jspx_imports_classes.add("models.Product");
    _jspx_imports_classes.add("dao.CartDao");
    _jspx_imports_classes.add("dao.ProductDao");
    _jspx_imports_classes.add("models.Customer");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write(" <title>AI.Tech - Artificial Intelligence HTML Template</title>\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Ubuntu:wght@500;700&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        .cart-icon-wrapper {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin-left: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .cart-icon-wrapper i {\r\n");
      out.write("            font-size: 22px;\r\n");
      out.write("            color: #000000;\r\n");
      out.write("        }\r\n");
      out.write("        .cart-badge {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: -8px;\r\n");
      out.write("            right: -10px;\r\n");
      out.write("            background-color: #ff3b3b;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-size: 11px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            line-height: 1;\r\n");
      out.write("            padding: 3px 6px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            min-width: 18px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	Customer c = null;
	if (session.getAttribute("customer") != null) {
		c = (Customer) session.getAttribute("customer");
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- Navbar Start -->\r\n");
      out.write("    <div class=\"container-fluid sticky-top\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <nav class=\"navbar navbar-expand-lg navbar-dark p-0\">\r\n");
      out.write("                <a href=\"index.jsp\" class=\"navbar-brand\">\r\n");
      out.write("                    <h1 class=\"text-white\">AI<span class=\"text-dark\">.</span>Tech</h1>\r\n");
      out.write("                </a>\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggler ms-auto me-0\" data-bs-toggle=\"collapse\"\r\n");
      out.write("                    data-bs-target=\"#navbarCollapse\">\r\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\">\r\n");
      out.write("                    <div class=\"navbar-nav ms-auto align-items-center\">\r\n");
      out.write("                        <a href=\"index.jsp\" class=\"nav-item nav-link active\">Home</a>\r\n");
      out.write("                        <a href=\"about.jsp\" class=\"nav-item nav-link\">About</a>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"nav-item dropdown\">\r\n");
      out.write("                            <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">Products</a>\r\n");
      out.write("                            <div class=\"dropdown-menu bg-light mt-2\">\r\n");
      out.write("                                <a href=\"#\" class=\"dropdown-item\">CRM and Sales</a>\r\n");
      out.write("                                <a href=\"#\" class=\"dropdown-item\">Content Creation and Marketing</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"nav-item dropdown\">\r\n");
      out.write("                            <a href=\"#\">Welcome,");
      out.print(c.getName());
      out.write("</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("						");

					List<Cart> cartList = CartDao.getCartByCusID(c.getId());
					
      out.write("\r\n");
      out.write("                        <a href=\"cart.jsp\" class=\"nav-item nav-link cart-icon-wrapper\">\r\n");
      out.write("                            <i class=\"bi bi-cart3\"></i>");
      out.print(cartList.size());
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Navbar End -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

	List<Cart> list = CartDao.getCartByCusID(c.getId());
	
      out.write("\r\n");
      out.write("	<div class=\"untree_co-section before-footer-section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row mb-5\">\r\n");
      out.write("				\r\n");
      out.write("					<div class=\"site-blocks-table\">\r\n");
      out.write("						<table class=\"table\">\r\n");
      out.write("							<thead>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th class=\"product-thumbnail\">Image</th>\r\n");
      out.write("									<th class=\"product-name\">Product</th>\r\n");
      out.write("									<th class=\"product-price\">Price</th>\r\n");
      out.write("									<th class=\"product-quantity\">Quantity</th>\r\n");
      out.write("									<th class=\"product-total\">Total</th>\r\n");
      out.write("									<th class=\"product-remove\">Remove</th>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</thead>\r\n");
      out.write("							<tbody>\r\n");
      out.write("								");

								int subtotal = 0;
								
      out.write("\r\n");
      out.write("								");

								for (Cart c1 : list) {
									subtotal = subtotal + c1.getTotal_price();
									Product p = ProductDao.getProductPid(c1.getPid());
								
      out.write("\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td class=\"product-thumbnail\"><img\r\n");
      out.write("										src=\"pimages/");
      out.print(p.getPimage());
      out.write("\" alt=\"Image\" class=\"img-fluid\"></td>\r\n");
      out.write("									<td class=\"product-name\">\r\n");
      out.write("										<h2 class=\"h5 text-black\">");
      out.print(p.getPname());
      out.write("</h2>\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>Rs. ");
      out.print(p.getPprice());
      out.write("</td>\r\n");
      out.write("									<td>\r\n");
      out.write("										<div\r\n");
      out.write("											class=\"input-group mb-3 d-flex align-items-center quantity-container\"\r\n");
      out.write("											style=\"max-width: 120px;\">\r\n");
      out.write("\r\n");
      out.write("											<form action=\"cartcontroller\" method=\"get\">\r\n");
      out.write("												<input type=\"hidden\" name=\"cart_id\"\r\n");
      out.write("													value=\"");
      out.print(c1.getCart_id());
      out.write("\"> <input type=\"number\"\r\n");
      out.write("													name=\"qty\" value=\"");
      out.print(c1.getQty());
      out.write("\"\r\n");
      out.write("													onchange=\"this.form.submit();\">\r\n");
      out.write("											</form>\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("									</td>\r\n");
      out.write("									<td>");
      out.print(c1.getTotal_price());
      out.write("</td>\r\n");
      out.write("									<td><a href=\"remove-cart.jsp?cart_id=");
      out.print(c1.getCart_id());
      out.write("\"\r\n");
      out.write("										class=\"btn btn-black btn-sm\">X</a></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								");

								}
								
      out.write("\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-6 pl-5\">\r\n");
      out.write("					<div class=\"row justify-content-end\">\r\n");
      out.write("						<div class=\"col-md-7\">\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-md-12 text-right border-bottom mb-5\">\r\n");
      out.write("									<h3 class=\"text-black h4 text-uppercase\">Cart Totals</h3>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"row mb-3\">\r\n");
      out.write("								<div class=\"col-md-6\">\r\n");
      out.write("									<span class=\"text-black\">Subtotal</span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-md-6 text-right\">\r\n");
      out.write("									<strong class=\"text-black\">Rs. ");
      out.print(subtotal);
      out.write("</strong>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"row mb-5\">\r\n");
      out.write("								<div class=\"col-md-6\">\r\n");
      out.write("									<span class=\"text-black\">GST 5%</span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-md-6 text-right\">\r\n");
      out.write("									\r\n");
      out.write("									<strong class=\"text-black\">Rs. </strong>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"row mb-5\">\r\n");
      out.write("								<div class=\"col-md-6\">\r\n");
      out.write("									<span class=\"text-black\">Total</span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-md-6 text-right\">\r\n");
      out.write("									<strong class=\"text-black\">Rs. ");
      out.print(subtotal);
      out.write("</strong>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-md-12\">\r\n");
      out.write("									<button class=\"btn btn-black btn-lg py-3 btn-block\"\r\n");
      out.write("										onclick=\"window.location='checkout.html'\">Proceed To\r\n");
      out.write("										Checkout</button>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
