/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-07-31 07:08:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import models.Member;
import models.Complaint;
import models.FunctionBooking;

public final class admin_002dhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("models.Member");
    _jspx_imports_classes.add("models.Complaint");
    _jspx_imports_classes.add("models.FunctionBooking");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Admin Home</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<h2>Welcome, ");
      out.print( ((models.Admin) session.getAttribute("admin")).getFullName() );
      out.write("</h2>\r\n");
      out.write("	<h3>Pending Member Approvals</h3>\r\n");
      out.write("\r\n");
      out.write("	");

		List<Member> pendingList = (List<Member>) request.getAttribute("pendingList");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
 if (pendingList == null || pendingList.isEmpty()) { 
      out.write("\r\n");
      out.write("		<p>No pending member requests.</p>\r\n");
      out.write("	");
 } else { 
      out.write("\r\n");
      out.write("		<table border=\"1\" cellpadding=\"8\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>Name</th>\r\n");
      out.write("				<th>Email</th>\r\n");
      out.write("				<th>Phone</th>\r\n");
      out.write("				<th>Flat No</th>\r\n");
      out.write("				<th>Registered On</th>\r\n");
      out.write("				<th>Action</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");
 for (Member m : pendingList) { 
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>");
      out.print( m.getFullName() );
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print( m.getEmail() );
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print( m.getPhoneNumber() );
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print( m.getFlatno() );
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print( m.getRegistrationDate() );
      out.write("</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<a href=\"admin?action=approve&memberid=");
      out.print( m.getMemberid() );
      out.write("\">Approve</a>\r\n");
      out.write("						&nbsp;|&nbsp;\r\n");
      out.write("						<a href=\"admin?action=reject&memberid=");
      out.print( m.getMemberid() );
      out.write("\">Reject</a>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<h3>Pending Complaints</h3>\r\n");
      out.write("\r\n");

	List<Complaint> pendingComplaints = (List<Complaint>) request.getAttribute("pendingComplaints");

      out.write("\r\n");
      out.write("\r\n");
 if (pendingComplaints == null || pendingComplaints.isEmpty()) { 
      out.write("\r\n");
      out.write("	<p>No pending complaints.</p>\r\n");
 } else { 
      out.write("\r\n");
      out.write("	<table border=\"1\" cellpadding=\"8\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th>Member ID</th>\r\n");
      out.write("			<th>Subject</th>\r\n");
      out.write("			<th>Description</th>\r\n");
      out.write("			<th>Date</th>\r\n");
      out.write("			<th>Action</th>\r\n");
      out.write("		</tr>\r\n");
      out.write("		");
 for (Complaint c : pendingComplaints) { 
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>");
      out.print( c.getMemberid() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( c.getSubject() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( c.getDescription() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( c.getComplaintDate() );
      out.write("</td>\r\n");
      out.write("				<td>\r\n");
      out.write("					<a href=\"admin?action=resolveComplaint&complaintid=");
      out.print( c.getComplaintid() );
      out.write("\">Mark Resolved</a>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("	</table>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<h3>Pending Function Booking Requests</h3>\r\n");

	List<FunctionBooking> pendingBookings = (List<FunctionBooking>) request.getAttribute("pendingBookings");

      out.write('\r');
      out.write('\n');
 if (pendingBookings == null || pendingBookings.isEmpty()) { 
      out.write("\r\n");
      out.write("	<p>No pending booking requests.</p>\r\n");
 } else { 
      out.write("\r\n");
      out.write("	<table border=\"1\" cellpadding=\"8\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th>Member ID</th>\r\n");
      out.write("			<th>Function Name</th>\r\n");
      out.write("			<th>Date</th>\r\n");
      out.write("			<th>Purpose</th>\r\n");
      out.write("			<th>Action</th>\r\n");
      out.write("		</tr>\r\n");
      out.write("		");
 for (FunctionBooking b : pendingBookings) { 
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>");
      out.print( b.getMemberid() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( b.getFunctionName() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( b.getFunctionDate() );
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print( b.getPurpose() );
      out.write("</td>\r\n");
      out.write("				<td>\r\n");
      out.write("					<a href=\"admin?action=approveBooking&bookingid=");
      out.print( b.getBookingid() );
      out.write("\">Approve</a>\r\n");
      out.write("					&nbsp;|&nbsp;\r\n");
      out.write("					<a href=\"admin?action=rejectBooking&bookingid=");
      out.print( b.getBookingid() );
      out.write("\">Reject</a>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("	</table>\r\n");
 } 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
