/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-07-20 07:14:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.ArrayList;
import dao.CartDao;
import dao.CartDaoImpl;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("dao.CartDaoImpl");
    _jspx_imports_classes.add("dao.CartDao");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Your Food Cart</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body { font-family: Arial, sans-serif; max-width: 600px; margin: 40px auto; }\r\n");
      out.write("        h1 { color: #333; }\r\n");
      out.write("        table { border-collapse: collapse; width: 100%; margin-top: 20px; }\r\n");
      out.write("        th, td { border: 1px solid #ccc; padding: 8px 12px; text-align: left; }\r\n");
      out.write("        th { background-color: #f4f4f4; }\r\n");
      out.write("        .empty-msg { color: #777; font-style: italic; margin-top: 20px; }\r\n");
      out.write("        form.inline { display: inline-block; margin-right: 8px; }\r\n");
      out.write("        .add-form { margin-top: 20px; padding: 15px; background: #fafafa; border: 1px solid #ddd; }\r\n");
      out.write("        .clear-btn { background: #d9534f; color: white; border: none; padding: 8px 14px; cursor: pointer; }\r\n");
      out.write("        .add-btn { background: #5cb85c; color: white; border: none; padding: 8px 14px; cursor: pointer; }\r\n");
      out.write("        input[type=text], input[type=number] { padding: 6px; margin-right: 8px; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h1>🛒 Your Food Cart</h1>\r\n");
      out.write("\r\n");

    // View reads cart data through the DAO, not by touching HttpSession directly.
    CartDao cartDao = new CartDaoImpl();
    ArrayList<String> cart = cartDao.getCartItems(request);

      out.write("\r\n");
      out.write("\r\n");
 if (cart.isEmpty()) { 
      out.write("\r\n");
      out.write("    <p class=\"empty-msg\">Your cart is empty. Add something delicious below!</p>\r\n");
 } else { 
      out.write("\r\n");
      out.write("    <table>\r\n");
      out.write("        <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>#</th>\r\n");
      out.write("                <th>Item</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("            ");

                int rowNum = 1;
                for (String item : cart) {
            
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>");
      out.print( rowNum++ );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( item );
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"add-form\">\r\n");
      out.write("    <h3>Add an item</h3>\r\n");
      out.write("    <form class=\"inline\" action=\"");
      out.print( request.getContextPath() );
      out.write("/cart\" method=\"post\">\r\n");
      out.write("        <input type=\"hidden\" name=\"action\" value=\"add\" />\r\n");
      out.write("        <input type=\"text\" name=\"itemName\" placeholder=\"Item name (e.g. Paneer Burger)\" required />\r\n");
      out.write("        <input type=\"number\" name=\"quantity\" placeholder=\"Qty\" min=\"1\" value=\"1\" style=\"width:70px;\" />\r\n");
      out.write("        <button type=\"submit\" class=\"add-btn\">Add to Cart</button>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<form action=\"");
      out.print( request.getContextPath() );
      out.write("/cart\" method=\"post\" style=\"margin-top: 15px;\">\r\n");
      out.write("    <input type=\"hidden\" name=\"action\" value=\"clear\" />\r\n");
      out.write("    <button type=\"submit\" class=\"clear-btn\">Clear Cart</button>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
